import os
import json
from dotenv import load_dotenv
from google import genai

# Load env variables and initialize client globally
load_dotenv()
client = genai.Client(api_key=os.getenv("API"))

def build_ai_detection_prompt(user_data: dict) -> str:
    # Safely extract up to the 5 most recent messages
    recent_messages = user_data.get("messages", [])[:5]
    username = user_data.get("username", "Unknown")
    
    # Create a minimal dictionary just for this prompt
    prompt_data = {
        "username": username,
        "recent_5_messages": recent_messages
    }

    prompt = f"""
You are an expert in detecting AI-generated text (like ChatGPT, Claude, etc.) on social media.

Input Data (Maximum 5 recent messages):
{prompt_data}

Analyze these texts specifically for hallmarks of Large Language Model generation. 
Look for things like:
- Overuse of transitional phrases ("Furthermore", "In conclusion", "It is important to note")
- Unnatural vocabulary ("delve", "tapestry", "testament", "multifaceted")
- Highly structured paragraphs with perfect grammar but lacking personal human anecdotes
- An overly enthusiastic, robotic, or universally agreeable tone
- Refusals or AI-like disclaimers ("As an AI", "I cannot confirm")

Task: Evaluate if the text feels naturally human or generated by an AI. Keep your output concise.

Return ONLY JSON in the following exact format:

{{
"is_ai_generated": true/false,
"ai_probability": 0.0,
"reasoning": "One concise sentence explaining why."
}}
"""
    return prompt

def run_text_authenticity_model(user_data: dict) -> dict:
    prompt = build_ai_detection_prompt(user_data)

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        
        # Clean the response for markdown backticks
        raw_text = response.text.strip()
        if raw_text.startswith("```json"):
            raw_text = raw_text[7:]
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3]
            
        return json.loads(raw_text.strip())
        
    except json.JSONDecodeError:
        return {"error": "Failed to parse LLM response into JSON", "ai_probability": 0.5, "is_ai_generated": False}
    except Exception as e:
        return {"error": str(e), "ai_probability": 0.5, "is_ai_generated": False}